// ============================================================
//  test BOT — CARD POOL
//  Add your own cards here! Format:
//  { id: 'unique_id', name: 'Character Name', series: 'Series',
//    rarity: 'R/E/L/MY/UR/LT', desc: 'Flavour text', image: 'https://...' }
// ============================================================

const { PULL_RATES } = require('./config');

const CARDS = [

  // ── Rare (R) ──────────────────────────────────────────────
  { id: 'naruto_r',         name: 'Naruto Uzumaki',          series: 'Naruto',                            rarity: 'R',  desc: 'The unpredictable ninja of the Hidden Leaf.',                        image: 'https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_uzumaki.png/revision/latest/scale-to-width-down/200' },
  { id: 'goku_r',           name: 'Goku',                    series: 'Dragon Ball Z',                     rarity: 'R',  desc: 'A pure-hearted Saiyan warrior.',                                     image: 'https://static.wikia.nocookie.net/dragonball/images/5/5b/Goku_Dragon_Ball_FighterZ.png/revision/latest/scale-to-width-down/200' },
  { id: 'luffy_r',          name: 'Monkey D. Luffy',         series: 'One Piece',                         rarity: 'R',  desc: 'Future King of the Pirates.',                                        image: 'https://static.wikia.nocookie.net/onepiece/images/6/6d/Monkey_D._Luffy_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'ichigo_r',         name: 'Ichigo Kurosaki',         series: 'Bleach',                            rarity: 'R',  desc: 'A Soul Reaper protecting the living world.',                         image: 'https://static.wikia.nocookie.net/bleach/images/2/28/Ichigo_Kurosaki_debut.png/revision/latest/scale-to-width-down/200' },
  { id: 'deku_r',           name: 'Izuku Midoriya',          series: 'My Hero Academia',                  rarity: 'R',  desc: 'The successor of One For All.',                                      image: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/1/18/Izuku_Midoriya_Hero_Costume_Gamma.png/revision/latest/scale-to-width-down/200' },
  { id: 'link_r',           name: 'Link',                    series: 'The Legend of Zelda',               rarity: 'R',  desc: 'The Hero of Time, chosen by the Triforce.',                          image: 'https://static.wikia.nocookie.net/zelda/images/4/4e/BotW_Link_Artwork.png/revision/latest/scale-to-width-down/200' },
  { id: 'cloud_r',          name: 'Cloud Strife',            series: 'Final Fantasy VII',                 rarity: 'R',  desc: 'Ex-SOLDIER turned mercenary.',                                       image: 'https://static.wikia.nocookie.net/finalfantasy/images/8/8e/Cloud_Strife_-_Crisis_Core_Reunion_art.png/revision/latest/scale-to-width-down/200' },
  { id: 'eren_r',           name: 'Eren Yeager',             series: 'Attack on Titan',                   rarity: 'R',  desc: 'A boy who swore to destroy the Titans.',                             image: 'https://static.wikia.nocookie.net/shingekinokyojin/images/b/b9/Eren_Yeager_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/200' },
  { id: 'pikachu_r',        name: 'Pikachu',                 series: 'Pokémon',                           rarity: 'R',  desc: 'The iconic Electric-type partner.',                                   image: 'https://static.wikia.nocookie.net/pokemon/images/0/0d/025Pikachu.png/revision/latest/scale-to-width-down/200' },
  { id: 'spike_r',          name: 'Spike Spiegel',           series: 'Cowboy Bebop',                      rarity: 'R',  desc: 'A bounty hunter drifting through space.',                            image: 'https://static.wikia.nocookie.net/cowboybebop/images/1/1c/Spike_Spiegel.png/revision/latest/scale-to-width-down/200' },
  // Bleach
  { id: 'rukia_r',          name: 'Rukia Kuchiki',           series: 'Bleach',                            rarity: 'R',  desc: 'A Soul Reaper who changed Ichigo\'s fate forever.',                  image: 'https://static.wikia.nocookie.net/bleach/images/1/19/Rukia_Kuchiki_Thousand-Year_Blood_War.png/revision/latest/scale-to-width-down/200' },
  { id: 'renji_r',          name: 'Renji Abarai',            series: 'Bleach',                            rarity: 'R',  desc: 'A hot-headed lieutenant with a serpent zanpakuto.',                  image: 'https://static.wikia.nocookie.net/bleach/images/4/42/Renji_Abarai_Thousand-Year_Blood_War.png/revision/latest/scale-to-width-down/200' },
  { id: 'uryu_r',           name: 'Uryu Ishida',             series: 'Bleach',                            rarity: 'R',  desc: 'The last Quincy, cold and precise.',                                  image: 'https://static.wikia.nocookie.net/bleach/images/a/ab/Uryuu_Ishida.png/revision/latest/scale-to-width-down/200' },
  { id: 'orihime_r',        name: 'Orihime Inoue',           series: 'Bleach',                            rarity: 'R',  desc: 'Her Shun Shun Rikka can reject reality itself.',                     image: 'https://static.wikia.nocookie.net/bleach/images/3/38/Orihime_Inoue_Thousand-Year_Blood_War.png/revision/latest/scale-to-width-down/200' },
  { id: 'chad_r',           name: 'Yasutora Sado',           series: 'Bleach',                            rarity: 'R',  desc: 'A gentle giant who fights only to protect others.',                  image: 'https://static.wikia.nocookie.net/bleach/images/5/5c/Yasutora_Sado.png/revision/latest/scale-to-width-down/200' },
  // JoJo's Bizarre Adventure
  { id: 'joseph_r',         name: 'Joseph Joestar',          series: 'JoJo\'s Bizarre Adventure',         rarity: 'R',  desc: 'Your next line is… "I knew you\'d say that!"',                       image: 'https://static.wikia.nocookie.net/jjba/images/2/2f/Joseph_Joestar_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'caesar_r',         name: 'Caesar Zeppeli',          series: 'JoJo\'s Bizarre Adventure',         rarity: 'R',  desc: 'A Hamon warrior of fierce elegance.',                                image: 'https://static.wikia.nocookie.net/jjba/images/5/5c/Caesar_Zeppeli_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'noriaki_r',        name: 'Noriaki Kakyoin',         series: 'JoJo\'s Bizarre Adventure',         rarity: 'R',  desc: 'Hierophant Green\'s loyal user.',                                     image: 'https://static.wikia.nocookie.net/jjba/images/1/17/Kakyoin_Noriaki_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  // One Piece
  { id: 'nami_r',           name: 'Nami',                    series: 'One Piece',                         rarity: 'R',  desc: 'Navigator of the Straw Hats, lover of treasure.',                   image: 'https://static.wikia.nocookie.net/onepiece/images/f/f3/Nami_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'usopp_r',          name: 'Usopp',                   series: 'One Piece',                         rarity: 'R',  desc: 'Brave warrior of the sea — when he needs to be.',                   image: 'https://static.wikia.nocookie.net/onepiece/images/e/e6/Usopp_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'chopper_r',        name: 'Tony Tony Chopper',       series: 'One Piece',                         rarity: 'R',  desc: 'A reindeer doctor with a Devil Fruit of many forms.',                image: 'https://static.wikia.nocookie.net/onepiece/images/4/44/Tony_Tony_Chopper_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'sanji_r',          name: 'Sanji',                   series: 'One Piece',                         rarity: 'R',  desc: 'A chef whose kicks blaze like a black flame.',                       image: 'https://static.wikia.nocookie.net/onepiece/images/c/ca/Sanji_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'robin_r',          name: 'Nico Robin',              series: 'One Piece',                         rarity: 'R',  desc: 'Archaeologist who can read the Poneglyphs.',                         image: 'https://static.wikia.nocookie.net/onepiece/images/8/8c/Nico_Robin_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  // Black Clover
  { id: 'asta_r',           name: 'Asta',                    series: 'Black Clover',                      rarity: 'R',  desc: 'A boy born without magic who never gives up.',                       image: 'https://static.wikia.nocookie.net/blackclover/images/b/bb/Asta_anime_profile.png/revision/latest/scale-to-width-down/200' },
  { id: 'noelle_r',         name: 'Noelle Silva',            series: 'Black Clover',                      rarity: 'R',  desc: 'Royal mage of the Black Bulls with water magic.',                    image: 'https://static.wikia.nocookie.net/blackclover/images/5/55/Noelle_Silva_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'yuno_r',           name: 'Yuno',                    series: 'Black Clover',                      rarity: 'R',  desc: 'Asta\'s rival, wielder of wind and star magic.',                     image: 'https://static.wikia.nocookie.net/blackclover/images/6/65/Yuno_anime_profile.png/revision/latest/scale-to-width-down/200' },
  // Demon Slayer
  { id: 'tanjiro_r',        name: 'Tanjiro Kamado',          series: 'Demon Slayer',                      rarity: 'R',  desc: 'A kind-hearted demon slayer with the Hinokami Kagura.',              image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/3/3c/Tanjiro_Kamado_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'nezuko_r',         name: 'Nezuko Kamado',           series: 'Demon Slayer',                      rarity: 'R',  desc: 'A demon who still protects humans with fierce love.',                 image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/a/af/Nezuko_Kamado_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'zenitsu_r',        name: 'Zenitsu Agatsuma',        series: 'Demon Slayer',                      rarity: 'R',  desc: 'Terrified of everything — until he falls asleep.',                   image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/8/8e/Zenitsu_Agatsuma_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'inosuke_r',        name: 'Inosuke Hashibira',       series: 'Demon Slayer',                      rarity: 'R',  desc: 'Wild boar-masked warrior raised in the mountains.',                  image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/8/89/Inosuke_Hashibira_Anime.png/revision/latest/scale-to-width-down/200' },
  // Fullmetal Alchemist: Brotherhood
  { id: 'edward_r',         name: 'Edward Elric',            series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'R',  desc: 'The Fullmetal Alchemist, short in stature, towering in will.',       image: 'https://static.wikia.nocookie.net/fma/images/2/23/Edward_Elric_2003_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'alphonse_r',       name: 'Alphonse Elric',          series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'R',  desc: 'A gentle soul sealed inside a suit of armour.',                      image: 'https://static.wikia.nocookie.net/fma/images/7/7e/Alphonse_Elric_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'winry_r',          name: 'Winry Rockbell',          series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'R',  desc: 'Mechanic genius and the heart of the Elric brothers.',               image: 'https://static.wikia.nocookie.net/fma/images/d/d0/Winry_Rockbell_Anime.png/revision/latest/scale-to-width-down/200' },
  // Sword Art Online
  { id: 'kirito_r',         name: 'Kirito',                  series: 'Sword Art Online',                  rarity: 'R',  desc: 'The Black Swordsman of Aincrad.',                                    image: 'https://static.wikia.nocookie.net/swordartonline/images/7/7c/Kirito_Avatar.png/revision/latest/scale-to-width-down/200' },
  { id: 'asuna_r',          name: 'Asuna',                   series: 'Sword Art Online',                  rarity: 'R',  desc: 'Lightning Flash, the fastest blade in SAO.',                        image: 'https://static.wikia.nocookie.net/swordartonline/images/a/a0/Asuna_Avatar.png/revision/latest/scale-to-width-down/200' },
  // Jujutsu Kaisen
  { id: 'itadori_r',        name: 'Yuji Itadori',            series: 'Jujutsu Kaisen',                    rarity: 'R',  desc: 'Host of Ryomen Sukuna, fighting for a proper death.',                image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/1/1c/Yuji_Itadori_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  { id: 'nobara_r',         name: 'Nobara Kugisaki',         series: 'Jujutsu Kaisen',                    rarity: 'R',  desc: 'Straw doll technique — don\'t underestimate her.',                   image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/e/e1/Nobara_Kugisaki_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  // Fairy Tail
  { id: 'natsu_r',          name: 'Natsu Dragneel',          series: 'Fairy Tail',                        rarity: 'R',  desc: 'The Fire Dragon Slayer of Fairy Tail.',                              image: 'https://static.wikia.nocookie.net/fairytail/images/f/f4/Natsu_Dragneel_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  { id: 'gray_r',           name: 'Gray Fullbuster',         series: 'Fairy Tail',                        rarity: 'R',  desc: 'An ice mage who keeps losing his clothes.',                          image: 'https://static.wikia.nocookie.net/fairytail/images/e/e8/Gray_Fullbuster_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  { id: 'erza_r',           name: 'Erza Scarlet',            series: 'Fairy Tail',                        rarity: 'R',  desc: 'Titania the Fairy Queen, requipping armour mid-battle.',             image: 'https://static.wikia.nocookie.net/fairytail/images/0/06/Erza_Scarlet_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  // Death Note
  { id: 'light_r',          name: 'Light Yagami',            series: 'Death Note',                        rarity: 'R',  desc: 'I am justice. I am the god of the new world.',                      image: 'https://static.wikia.nocookie.net/deathnote/images/9/9d/Light_Yagami_profile.png/revision/latest/scale-to-width-down/200' },
  { id: 'l_r',              name: 'L Lawliet',               series: 'Death Note',                        rarity: 'R',  desc: 'The world\'s greatest detective — sitting oddly.',                   image: 'https://static.wikia.nocookie.net/deathnote/images/0/02/L_Lawliet_profile.png/revision/latest/scale-to-width-down/200' },
  // Mob Psycho 100
  { id: 'mob_r',            name: 'Shigeo Kageyama',         series: 'Mob Psycho 100',                    rarity: 'R',  desc: 'A boy suppressing psychic power that shakes the earth.',             image: 'https://static.wikia.nocookie.net/mob-psycho-100/images/1/10/Mob.png/revision/latest/scale-to-width-down/200' },
  { id: 'reigen_r',         name: 'Reigen Arataka',          series: 'Mob Psycho 100',                    rarity: 'R',  desc: 'Greatest psychic of the century — citation needed.',                 image: 'https://static.wikia.nocookie.net/mob-psycho-100/images/9/9d/Reigen.png/revision/latest/scale-to-width-down/200' },
  // Hunter x Hunter
  { id: 'gon_r',            name: 'Gon Freecss',             series: 'Hunter x Hunter',                   rarity: 'R',  desc: 'An innocent boy with limitless hidden potential.',                   image: 'https://static.wikia.nocookie.net/hunterxhunter/images/d/df/Gon_Freecss_%282011%29_character_art.png/revision/latest/scale-to-width-down/200' },
  { id: 'kurapika_r',       name: 'Kurapika',                series: 'Hunter x Hunter',                   rarity: 'R',  desc: 'A Kurta survivor driven by vengeance.',                              image: 'https://static.wikia.nocookie.net/hunterxhunter/images/6/66/Kurapika_%282011%29_character_art.png/revision/latest/scale-to-width-down/200' },
  // Chainsaw Man
  { id: 'denji_r',          name: 'Denji',                   series: 'Chainsaw Man',                      rarity: 'R',  desc: 'A devil hunter with a chainsaw heart.',                              image: 'https://static.wikia.nocookie.net/chainsaw-man/images/d/dc/Denji_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'power_r',          name: 'Power',                   series: 'Chainsaw Man',                      rarity: 'R',  desc: 'Blood Fiend and certified chaotic ally.',                            image: 'https://static.wikia.nocookie.net/chainsaw-man/images/1/18/Power_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  // Spy x Family
  { id: 'loid_r',           name: 'Loid Forger',             series: 'Spy x Family',                      rarity: 'R',  desc: 'Spy Twilight, master of disguise and fake fatherhood.',              image: 'https://static.wikia.nocookie.net/spy-x-family/images/f/f7/Loid_Forger_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'yor_r',            name: 'Yor Forger',              series: 'Spy x Family',                      rarity: 'R',  desc: 'An assassin who genuinely tries her best at cooking.',              image: 'https://static.wikia.nocookie.net/spy-x-family/images/5/55/Yor_Forger_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'anya_r',           name: 'Anya Forger',             series: 'Spy x Family',                      rarity: 'R',  desc: 'A telepath who just wants her family to stay together.',             image: 'https://static.wikia.nocookie.net/spy-x-family/images/c/ce/Anya_Forger_anime.png/revision/latest/scale-to-width-down/200' },
  // Re:Zero
  { id: 'subaru_r',         name: 'Subaru Natsuki',          series: 'Re:Zero',                           rarity: 'R',  desc: 'An ordinary teen who dies repeatedly to save others.',               image: 'https://static.wikia.nocookie.net/rezero/images/3/37/Subaru_Natsuki_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'emilia_r',         name: 'Emilia',                  series: 'Re:Zero',                           rarity: 'R',  desc: 'A half-elf candidate for the royal throne.',                         image: 'https://static.wikia.nocookie.net/rezero/images/a/ac/Emilia_Anime.png/revision/latest/scale-to-width-down/200' },
  // Gintama
  { id: 'gintoki_r',        name: 'Gintoki Sakata',          series: 'Gintama',                           rarity: 'R',  desc: 'The White Demon, now running an odd-jobs business.',                 image: 'https://static.wikia.nocookie.net/gintama/images/4/4a/Gintoki.png/revision/latest/scale-to-width-down/200' },
  // Inuyasha
  { id: 'inuyasha_r',       name: 'Inuyasha',                series: 'Inuyasha',                          rarity: 'R',  desc: 'Half-demon with the Tessaiga, caught between two worlds.',           image: 'https://static.wikia.nocookie.net/inuyasha/images/8/8e/Inuyasha_profile.png/revision/latest/scale-to-width-down/200' },
  // Steins;Gate
  { id: 'okabe_r',          name: 'Rintaro Okabe',           series: 'Steins;Gate',                       rarity: 'R',  desc: 'Mad scientist — El Psy Kongroo.',                                    image: 'https://static.wikia.nocookie.net/steins-gate/images/a/a0/Okabe_Rintaro.png/revision/latest/scale-to-width-down/200' },
  // Yu Yu Hakusho
  { id: 'yusuke_r',         name: 'Yusuke Urameshi',         series: 'Yu Yu Hakusho',                     rarity: 'R',  desc: 'A delinquent who died saving a kid and became a Spirit Detective.', image: 'https://static.wikia.nocookie.net/yuyu-hakusho/images/1/1e/Yusuke_Urameshi.png/revision/latest/scale-to-width-down/200' },
  // Overlord
  { id: 'albedo_e',         name: 'Albedo',                  series: 'Overlord',                          rarity: 'E',  desc: 'Guardian Overseer of Nazarick, devoted to Ainz without question.',   image: 'https://static.wikia.nocookie.net/overlordmaruyama/images/9/9f/Albedo_Anime.png/revision/latest/scale-to-width-down/200' },
  // Death Note
  { id: 'near_l',           name: 'Near',                    series: 'Death Note',                        rarity: 'L',  desc: 'L\'s true successor — he cornered Kira with logic and toys.',        image: 'https://static.wikia.nocookie.net/deathnote/images/0/07/Near_profile.png/revision/latest/scale-to-width-down/200' },

  // ── Epic (E) ──────────────────────────────────────────────
  { id: 'sasuke_e',         name: 'Sasuke Uchiha',           series: 'Naruto',                            rarity: 'E',  desc: 'Last survivor of the Uchiha clan.',                                  image: 'https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_newshot.png/revision/latest/scale-to-width-down/200' },
  { id: 'vegeta_e',         name: 'Vegeta',                  series: 'Dragon Ball Z',                     rarity: 'E',  desc: 'The proud Prince of all Saiyans.',                                   image: 'https://static.wikia.nocookie.net/dragonball/images/e/ea/VegetaSSJFutureTrunksSaga.png/revision/latest/scale-to-width-down/200' },
  { id: 'zoro_e',           name: 'Roronoa Zoro',            series: 'One Piece',                         rarity: 'E',  desc: 'Swordsman aiming to be the world\'s greatest.',                      image: 'https://static.wikia.nocookie.net/onepiece/images/d/d0/Roronoa_Zoro_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'bakugo_e',         name: 'Katsuki Bakugo',          series: 'My Hero Academia',                  rarity: 'E',  desc: 'Explosive hero with a fiery spirit.',                                image: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/0/0c/Katsuki_Bakugo_Hero_Costume_Beta_Full.png/revision/latest/scale-to-width-down/200' },
  { id: 'levi_e',           name: 'Levi Ackerman',           series: 'Attack on Titan',                   rarity: 'E',  desc: 'Humanity\'s strongest soldier.',                                     image: 'https://static.wikia.nocookie.net/shingekinokyojin/images/c/c8/Levi_Ackerman_%28Anime%29_character_image.png/revision/latest/scale-to-width-down/200' },
  { id: 'kratos_e',         name: 'Kratos',                  series: 'God of War',                        rarity: 'E',  desc: 'The Ghost of Sparta, slayer of gods.',                               image: 'https://static.wikia.nocookie.net/godofwar/images/6/6e/Kratos_GoW_2018.png/revision/latest/scale-to-width-down/200' },
  { id: 'sephiroth_e',      name: 'Sephiroth',               series: 'Final Fantasy VII',                 rarity: 'E',  desc: 'A legendary SOLDIER turned destroyer.',                              image: 'https://static.wikia.nocookie.net/finalfantasy/images/4/4d/Sephiroth_artwork.png/revision/latest/scale-to-width-down/200' },
  { id: 'killua_e',         name: 'Killua Zoldyck',          series: 'Hunter x Hunter',                   rarity: 'E',  desc: 'An assassin heir with lightning reflexes.',                          image: 'https://static.wikia.nocookie.net/hunterxhunter/images/a/a0/Killua_Zoldyck_%282011%29_character_art.png/revision/latest/scale-to-width-down/200' },
  // Bleach
  { id: 'byakuya_e',        name: 'Byakuya Kuchiki',         series: 'Bleach',                            rarity: 'E',  desc: 'Pride and petals — the captain of the 6th Division.',               image: 'https://static.wikia.nocookie.net/bleach/images/f/f6/Byakuya_Kuchiki_Thousand-Year_Blood_War.png/revision/latest/scale-to-width-down/200' },
  { id: 'grimmjow_e',       name: 'Grimmjow Jaegerjaquez',   series: 'Bleach',                            rarity: 'E',  desc: 'Sixth Espada. Chaos given form.',                                    image: 'https://static.wikia.nocookie.net/bleach/images/8/84/Grimmjow_Jaegerjaquez.png/revision/latest/scale-to-width-down/200' },
  { id: 'ulquiorra_e',      name: 'Ulquiorra Cifer',         series: 'Bleach',                            rarity: 'E',  desc: 'Fourth Espada. Nihilism made flesh.',                               image: 'https://static.wikia.nocookie.net/bleach/images/4/4f/Ulquiorra_Cifer.png/revision/latest/scale-to-width-down/200' },
  // JoJo's Bizarre Adventure
  { id: 'jotaro_e',         name: 'Jotaro Kujo',             series: 'JoJo\'s Bizarre Adventure',         rarity: 'E',  desc: 'Yare yare daze. Star Platinum: The World.',                          image: 'https://static.wikia.nocookie.net/jjba/images/0/00/Jotaro_Kujo_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'giorno_e',         name: 'Giorno Giovanna',         series: 'JoJo\'s Bizarre Adventure',         rarity: 'E',  desc: 'I, Giorno Giovanna, have a dream.',                                  image: 'https://static.wikia.nocookie.net/jjba/images/3/34/Giorno_Giovanna_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'josuke_e',         name: 'Josuke Higashikata',      series: 'JoJo\'s Bizarre Adventure',         rarity: 'E',  desc: 'Don\'t insult the hair. Crazy Diamond will fix that.',              image: 'https://static.wikia.nocookie.net/jjba/images/e/e8/Josuke_Higashikata_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  // One Piece
  { id: 'ace_e',            name: 'Portgas D. Ace',          series: 'One Piece',                         rarity: 'E',  desc: 'Fire Fist Ace — Whitebeard\'s beloved son.',                        image: 'https://static.wikia.nocookie.net/onepiece/images/a/a0/Portgas_D._Ace_Anime_Pre_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'law_e',            name: 'Trafalgar D. Water Law',  series: 'One Piece',                         rarity: 'E',  desc: 'The Surgeon of Death and his ROOM ability.',                        image: 'https://static.wikia.nocookie.net/onepiece/images/3/30/Trafalgar_D._Water_Law_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'kid_e',            name: 'Eustass Kid',             series: 'One Piece',                         rarity: 'E',  desc: 'A magnetic supernova with a reckless streak.',                       image: 'https://static.wikia.nocookie.net/onepiece/images/7/71/Eustass_Kid_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  // Black Clover
  { id: 'yami_e',           name: 'Yami Sukehiro',           series: 'Black Clover',                      rarity: 'E',  desc: 'Dark magic captain who exceeds his limits daily.',                   image: 'https://static.wikia.nocookie.net/blackclover/images/e/e1/Yami_Sukehiro_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'julius_e',         name: 'Julius Novachrono',       series: 'Black Clover',                      rarity: 'E',  desc: 'The Wizard King, obsessed with new magic.',                          image: 'https://static.wikia.nocookie.net/blackclover/images/6/62/Julius_Novachrono_Anime.png/revision/latest/scale-to-width-down/200' },
  // Demon Slayer
  { id: 'rengoku_e',        name: 'Kyojuro Rengoku',         series: 'Demon Slayer',                      rarity: 'E',  desc: 'Flame Hashira. Set your heart ablaze!',                             image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/2/23/Kyojuro_Rengoku_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'tengen_e',         name: 'Tengen Uzui',             series: 'Demon Slayer',                      rarity: 'E',  desc: 'Sound Hashira. Flamboyant by choice, lethal by skill.',             image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/1/11/Tengen_Uzui_Anime.png/revision/latest/scale-to-width-down/200' },
  // Fullmetal Alchemist: Brotherhood
  { id: 'roy_e',            name: 'Roy Mustang',             series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'E',  desc: 'The Flame Alchemist aiming for the top.',                            image: 'https://static.wikia.nocookie.net/fma/images/d/d8/Roy_Mustang_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'armstrong_e',      name: 'Alex Louis Armstrong',    series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'E',  desc: 'Strong-arm Alchemist — and proud of it.',                           image: 'https://static.wikia.nocookie.net/fma/images/3/31/Alex_Louis_Armstrong_Anime.png/revision/latest/scale-to-width-down/200' },
  // Jujutsu Kaisen
  { id: 'gojo_e',           name: 'Satoru Gojo',             series: 'Jujutsu Kaisen',                    rarity: 'E',  desc: 'The strongest — Infinity in the palm of his hand.',                  image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/f/f5/Satoru_Gojo_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  { id: 'todo_e',           name: 'Aoi Todo',                series: 'Jujutsu Kaisen',                    rarity: 'E',  desc: 'What\'s your type? Boogie Woogie!',                                  image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/a/ae/Aoi_Todo_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  // Fairy Tail
  { id: 'laxus_e',          name: 'Laxus Dreyar',            series: 'Fairy Tail',                        rarity: 'E',  desc: 'Lightning Dragon Slayer and Fairy Tail\'s thunder god.',             image: 'https://static.wikia.nocookie.net/fairytail/images/7/7a/Laxus_Dreyar_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  { id: 'gildarts_e',       name: 'Gildarts Clive',          series: 'Fairy Tail',                        rarity: 'E',  desc: 'Fairy Tail\'s ace, whose Crush magic breaks anything.',              image: 'https://static.wikia.nocookie.net/fairytail/images/5/5e/Gildarts_Clive_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  // Yu Yu Hakusho
  { id: 'hiei_e',           name: 'Hiei',                    series: 'Yu Yu Hakusho',                     rarity: 'E',  desc: 'The Forbidden Child, wielder of the Dragon of the Darkness Flame.', image: 'https://static.wikia.nocookie.net/yuyu-hakusho/images/c/ce/Hiei.png/revision/latest/scale-to-width-down/200' },
  { id: 'kurama_e',         name: 'Kurama',                  series: 'Yu Yu Hakusho',                     rarity: 'E',  desc: 'A fox demon reborn — his Rose Whip is merciless.',                  image: 'https://static.wikia.nocookie.net/yuyu-hakusho/images/2/2c/Kurama.png/revision/latest/scale-to-width-down/200' },
  // Re:Zero
  { id: 'rem_e',            name: 'Rem',                     series: 'Re:Zero',                           rarity: 'E',  desc: 'A demon maid who loves with her whole heart.',                       image: 'https://static.wikia.nocookie.net/rezero/images/8/80/Rem_Anime.png/revision/latest/scale-to-width-down/200' },
  // Seven Deadly Sins
  { id: 'ban_e',            name: 'Ban',                     series: 'The Seven Deadly Sins',             rarity: 'E',  desc: 'The Undead Fox\'s Sin of Greed.',                                    image: 'https://static.wikia.nocookie.net/nanatsu-no-taizai/images/9/9c/Ban_Anime.png/revision/latest/scale-to-width-down/200' },
  // Vinland Saga
  { id: 'thorfinn_e',       name: 'Thorfinn',                series: 'Vinland Saga',                      rarity: 'E',  desc: 'A boy forged by war who chose to lay down his blade.',               image: 'https://static.wikia.nocookie.net/vinlandsaga/images/5/55/Thorfinn_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'askeladd_e',       name: 'Askeladd',                series: 'Vinland Saga',                      rarity: 'E',  desc: 'A cunning chieftain who plays every side.',                          image: 'https://static.wikia.nocookie.net/vinlandsaga/images/a/a1/Askeladd_Anime.png/revision/latest/scale-to-width-down/200' },
  // Code Geass
  { id: 'lelouch_e',        name: 'Lelouch vi Britannia',    series: 'Code Geass',                        rarity: 'E',  desc: 'Zero — the chess master who bet the world.',                        image: 'https://static.wikia.nocookie.net/codegeass/images/0/04/Lelouch_vi_Britannia.png/revision/latest/scale-to-width-down/200' },
  // Gurren Lagann
  { id: 'kamina_e',         name: 'Kamina',                  series: 'Gurren Lagann',                     rarity: 'E',  desc: 'Believe in the me who believes in you!',                            image: 'https://static.wikia.nocookie.net/gurren-lagann/images/b/b4/Kamina.png/revision/latest/scale-to-width-down/200' },
  // Chainsaw Man
  { id: 'makima_e',         name: 'Makima',                  series: 'Chainsaw Man',                      rarity: 'E',  desc: 'Control Devil in disguise. Everything bows to her.',                 image: 'https://static.wikia.nocookie.net/chainsaw-man/images/9/9f/Makima_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  // Black Butler
  { id: 'sebastian_e',      name: 'Sebastian Michaelis',     series: 'Black Butler',                      rarity: 'E',  desc: 'One hell of a butler. Demon by nature.',                            image: 'https://static.wikia.nocookie.net/kuroshitsuji/images/3/3a/Sebastian_Michaelis_Anime.png/revision/latest/scale-to-width-down/200' },

  // ── Legendary (L) ─────────────────────────────────────────
  { id: 'itachi_l',         name: 'Itachi Uchiha',           series: 'Naruto',                            rarity: 'L',  desc: 'A shinobi who bore the weight of sacrifice.',                       image: 'https://static.wikia.nocookie.net/naruto/images/b/bb/Itachi.png/revision/latest/scale-to-width-down/200' },
  { id: 'goku_ssj4_l',      name: 'Goku SSJ4',               series: 'Dragon Ball GT',                    rarity: 'L',  desc: 'The pinnacle of Saiyan transformation.',                             image: 'https://static.wikia.nocookie.net/dragonball/images/5/50/Goku_SSJ4_render.png/revision/latest/scale-to-width-down/200' },
  { id: 'shanks_l',         name: 'Red-Hair Shanks',         series: 'One Piece',                         rarity: 'L',  desc: 'One of the Four Emperors of the Sea.',                               image: 'https://static.wikia.nocookie.net/onepiece/images/e/e0/Shanks_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'allmight_l',       name: 'All Might',               series: 'My Hero Academia',                  rarity: 'L',  desc: 'The Symbol of Peace. Plus Ultra!',                                   image: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/3/3e/All_Might_Hero_Form.png/revision/latest/scale-to-width-down/200' },
  { id: 'genos_l',          name: 'Genos',                   series: 'One Punch Man',                     rarity: 'L',  desc: 'A cyborg hero seeking the truth of his power.',                     image: 'https://static.wikia.nocookie.net/onepunchman/images/d/db/Genos_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'hisoka_l',         name: 'Hisoka Morow',            series: 'Hunter x Hunter',                   rarity: 'L',  desc: 'A twisted magician who lives to fight the strong.',                  image: 'https://static.wikia.nocookie.net/hunterxhunter/images/8/8a/Hisoka_%282011%29_character_art.png/revision/latest/scale-to-width-down/200' },
  // Bleach
  { id: 'aizen_l',          name: 'Sosuke Aizen',            series: 'Bleach',                            rarity: 'L',  desc: 'Omniscient, omnipotent — and he\'s been fooling you all along.',     image: 'https://static.wikia.nocookie.net/bleach/images/f/f4/Sosuke_Aizen.png/revision/latest/scale-to-width-down/200' },
  { id: 'gin_l',            name: 'Gin Ichimaru',            series: 'Bleach',                            rarity: 'L',  desc: 'A silver smile that hides the sharpest blade.',                     image: 'https://static.wikia.nocookie.net/bleach/images/8/83/Gin_Ichimaru.png/revision/latest/scale-to-width-down/200' },
  // JoJo's Bizarre Adventure
  { id: 'dio_l',            name: 'Dio Brando',              series: 'JoJo\'s Bizarre Adventure',         rarity: 'L',  desc: 'WRYYY! The World stops time itself.',                               image: 'https://static.wikia.nocookie.net/jjba/images/d/d1/Dio_Brando_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  // One Piece
  { id: 'mihawk_l',         name: 'Dracule Mihawk',          series: 'One Piece',                         rarity: 'L',  desc: 'Greatest swordsman in the world. Zoro\'s goal.',                    image: 'https://static.wikia.nocookie.net/onepiece/images/a/ac/Dracule_Mihawk_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  // Black Clover
  { id: 'licht_l',          name: 'Licht',                   series: 'Black Clover',                      rarity: 'L',  desc: 'The first Magic Knight, carrying a nation\'s grief.',                image: 'https://static.wikia.nocookie.net/blackclover/images/f/f5/Licht_Anime.png/revision/latest/scale-to-width-down/200' },
  // Fullmetal Alchemist: Brotherhood
  { id: 'father_l',         name: 'Father',                  series: 'Fullmetal Alchemist: Brotherhood',  rarity: 'L',  desc: 'The dwarf in the flask who consumed a God.',                        image: 'https://static.wikia.nocookie.net/fma/images/e/e5/Father_Anime.png/revision/latest/scale-to-width-down/200' },
  // Jujutsu Kaisen
  { id: 'yuta_l',           name: 'Yuta Okkotsu',            series: 'Jujutsu Kaisen',                    rarity: 'L',  desc: 'Special Grade — his cursed energy is unmatched.',                   image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/9/9b/Yuta_Okkotsu_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  // Fairy Tail
  { id: 'mavis_l',          name: 'Mavis Vermillion',        series: 'Fairy Tail',                        rarity: 'L',  desc: 'First Master of Fairy Tail, the Fairy Tactician.',                  image: 'https://static.wikia.nocookie.net/fairytail/images/4/4c/Mavis_Vermillion_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  // Hunter x Hunter
  { id: 'netero_l',         name: 'Isaac Netero',            series: 'Hunter x Hunter',                   rarity: 'L',  desc: 'The 12th Chairman — a prayer that could kill gods.',                 image: 'https://static.wikia.nocookie.net/hunterxhunter/images/2/29/Isaac_Netero_%282011%29_character_art.png/revision/latest/scale-to-width-down/200' },
  // Gurren Lagann
  { id: 'simon_l',          name: 'Simon the Digger',        series: 'Gurren Lagann',                     rarity: 'L',  desc: 'From a tunnel-digging boy to the driller who pierces the heavens.',  image: 'https://static.wikia.nocookie.net/gurren-lagann/images/8/87/Simon.png/revision/latest/scale-to-width-down/200' },
  // That Time I Got Reincarnated as a Slime
  { id: 'rimuru_l',         name: 'Rimuru Tempest',          series: 'That Time I Got Reincarnated as a Slime', rarity: 'L', desc: 'A slime who built a nation and became a True Demon Lord.',      image: 'https://static.wikia.nocookie.net/tensura/images/8/87/Rimuru_Anime.png/revision/latest/scale-to-width-down/200' },

  // ── Mythical (MY) ─────────────────────────────────────────
  { id: 'madara_my',        name: 'Madara Uchiha',           series: 'Naruto',                            rarity: 'MY', desc: 'A god of shinobi with unrivalled power.',                            image: 'https://static.wikia.nocookie.net/naruto/images/5/52/Madara_Uchiha.png/revision/latest/scale-to-width-down/200' },
  { id: 'beerus_my',        name: 'Beerus',                  series: 'Dragon Ball Super',                 rarity: 'MY', desc: 'God of Destruction. Do not wake him.',                               image: 'https://static.wikia.nocookie.net/dragonball/images/e/e6/BeerusDB.png/revision/latest/scale-to-width-down/200' },
  { id: 'whitebeard_my',    name: 'Whitebeard',              series: 'One Piece',                         rarity: 'MY', desc: 'The man who stood atop the world.',                                  image: 'https://static.wikia.nocookie.net/onepiece/images/e/ed/Edward_Newgate_Anime_Pre_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'saitama_my',       name: 'Saitama',                 series: 'One Punch Man',                     rarity: 'MY', desc: 'Defeated every enemy with a single punch.',                          image: 'https://static.wikia.nocookie.net/onepunchman/images/8/8a/Saitama_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'mewtwo_my',        name: 'Mewtwo',                  series: 'Pokémon',                           rarity: 'MY', desc: 'A genetically engineered Pokémon of immense psy-power.',            image: 'https://static.wikia.nocookie.net/pokemon/images/7/78/150Mewtwo.png/revision/latest/scale-to-width-down/200' },
  // New Mythical
  { id: 'yhwach_my',        name: 'Yhwach',                  series: 'Bleach',                            rarity: 'MY', desc: 'The Almighty — he sees and rewrites all futures.',                   image: 'https://static.wikia.nocookie.net/bleach/images/1/17/Yhwach.png/revision/latest/scale-to-width-down/200' },
  { id: 'kira_my',          name: 'Yoshikage Kira',          series: 'JoJo\'s Bizarre Adventure',         rarity: 'MY', desc: 'All he wants is a quiet life. Killer Queen won\'t let you stop him.', image: 'https://static.wikia.nocookie.net/jjba/images/2/28/Yoshikage_Kira_infobox_anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'kaido_my',         name: 'Kaido',                   series: 'One Piece',                         rarity: 'MY', desc: 'The world\'s strongest creature. Couldn\'t be killed.',              image: 'https://static.wikia.nocookie.net/onepiece/images/5/55/Kaido_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'muzan_my',         name: 'Muzan Kibutsuji',         series: 'Demon Slayer',                      rarity: 'MY', desc: 'King of Demons. The source of all evil in the night.',              image: 'https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/0/00/Muzan_Kibutsuji_Anime.png/revision/latest/scale-to-width-down/200' },
  { id: 'sukuna_my',        name: 'Ryomen Sukuna',           series: 'Jujutsu Kaisen',                    rarity: 'MY', desc: 'King of Curses — even sealed in fingers, none compare.',             image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/7/7e/Ryomen_Sukuna_%28Anime%29.png/revision/latest/scale-to-width-down/200' },
  { id: 'acnologia_my',     name: 'Acnologia',               series: 'Fairy Tail',                        rarity: 'MY', desc: 'The Black Dragon of the Apocalypse, annihilator of magic.',          image: 'https://static.wikia.nocookie.net/fairytail/images/5/5c/Acnologia_Anime_S2.png/revision/latest/scale-to-width-down/200' },
  { id: 'escanor_my',       name: 'Escanor',                 series: 'The Seven Deadly Sins',             rarity: 'MY', desc: 'The Lion\'s Sin of Pride. At noon, none can surpass him.',           image: 'https://static.wikia.nocookie.net/nanatsu-no-taizai/images/7/73/Escanor_Anime.png/revision/latest/scale-to-width-down/200' },

  // ── Ultra-Rare (UR) ───────────────────────────────────────
  { id: 'kaguya_ur',        name: 'Kaguya Ōtsutsuki',        series: 'Naruto',                            rarity: 'UR', desc: 'The progenitor of chakra itself.',                                   image: 'https://static.wikia.nocookie.net/naruto/images/6/60/Kaguya_%C5%8Ctsutsuki.png/revision/latest/scale-to-width-down/200' },
  { id: 'zeno_ur',          name: 'Zeno',                    series: 'Dragon Ball Super',                 rarity: 'UR', desc: 'The Omni-King who can erase universes.',                             image: 'https://static.wikia.nocookie.net/dragonball/images/0/04/ZenoFull.png/revision/latest/scale-to-width-down/200' },
  { id: 'joyboy_ur',        name: 'Joy Boy',                 series: 'One Piece',                         rarity: 'UR', desc: 'A legend from the Void Century.',                                    image: 'https://static.wikia.nocookie.net/onepiece/images/4/48/Joy_Boy_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'arceus_ur',        name: 'Arceus',                  series: 'Pokémon',                           rarity: 'UR', desc: 'The Alpha Pokémon who shaped the universe.',                         image: 'https://static.wikia.nocookie.net/pokemon/images/2/21/493Arceus.png/revision/latest/scale-to-width-down/200' },
  // New Ultra-Rare
  { id: 'ichigo_bankai_ur', name: 'Ichigo (True Bankai)',    series: 'Bleach',                            rarity: 'UR', desc: 'The final convergence of Soul Reaper, Hollow, and Quincy.',          image: 'https://static.wikia.nocookie.net/bleach/images/8/8e/Ichigo_True_Bankai.png/revision/latest/scale-to-width-down/200' },
  { id: 'blackbeard_ur',    name: 'Marshall D. Teach',       series: 'One Piece',                         rarity: 'UR', desc: 'Two Devil Fruits. Darkness swallows all, quakes shatter all.',       image: 'https://static.wikia.nocookie.net/onepiece/images/8/87/Marshall_D._Teach_Anime_Post_Timeskip_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'dio_wr_ur',        name: 'DIO (The World)',         series: 'JoJo\'s Bizarre Adventure',         rarity: 'UR', desc: 'ZA WARUDO! Time stops for him and him alone.',                      image: 'https://static.wikia.nocookie.net/jjba/images/d/d1/Dio_Brando_infobox_anime.png/revision/latest/scale-to-width-down/200' },

  // ── Limited (LT) ──────────────────────────────────────────
  { id: 'sage_naruto_lt',   name: 'Naruto (Six Paths Sage)', series: 'Naruto',                            rarity: 'LT', desc: 'Bestowed power by the Sage of Six Paths himself.',                  image: 'https://static.wikia.nocookie.net/naruto/images/0/0b/Six_Paths_Sage_Mode.png/revision/latest/scale-to-width-down/200' },
  { id: 'ultra_goku_lt',    name: 'Goku (Ultra Instinct)',   series: 'Dragon Ball Super',                 rarity: 'LT', desc: 'A state beyond the gods — pure autonomous movement.',               image: 'https://static.wikia.nocookie.net/dragonball/images/4/4f/GokuUltraInstinct.png/revision/latest/scale-to-width-down/200' },
  { id: 'gear5_luffy_lt',   name: 'Luffy (Gear 5)',          series: 'One Piece',                         rarity: 'LT', desc: 'The most ridiculous power in the world. Joy Boy awakened.',         image: 'https://static.wikia.nocookie.net/onepiece/images/0/08/Monkey_D._Luffy_Gear_5_Anime_Infobox.png/revision/latest/scale-to-width-down/200' },
  { id: 'sukuna_fp_lt',     name: 'Sukuna (Full Power)',     series: 'Jujutsu Kaisen',                    rarity: 'LT', desc: 'Heian-era pinnacle. Cleave and Dismantle erasing existence.',        image: 'https://static.wikia.nocookie.net/jujutsu-kaisen/images/7/7e/Ryomen_Sukuna_%28Anime%29.png/revision/latest/scale-to-width-down/200' },

];

/**
 * Pull a random card weighted by PULL_RATES.
 */
function pullCard() {
  const roll = Math.random() * 100;
  let cumulative = 0;
  let chosen = 'R';

  for (const [rarity, rate] of Object.entries(PULL_RATES)) {
    cumulative += rate;
    if (roll < cumulative) { chosen = rarity; break; }
  }

  const pool = CARDS.filter(c => c.rarity === chosen);
  return pool.length ? pool[Math.floor(Math.random() * pool.length)] : CARDS[0];
}

module.exports = { CARDS, pullCard };
